server:
  port: 8083
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080/demo
    username: root
    password: 123123
mybatis:
  mapper-locations: classpath:mapper/*.xml