server:
  port: 8083
  servlet:
    context-path: /
  max-http-header-size: 4048576

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8080/demo
    username: root
    password: Cph1996@
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapper/*.xml