server:
  port: 8083
  servlet:
    context-path: /
  max-http-header-size: 4048576

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.84.248:3306/wh_road_bridge?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: Cph1996@
    druid:
      aop-patterns: com.example.detect.entity.* #监控springbean
      filters: stat, wall #底层开启功能，stat(sql监控)，wall(防火墙)

      stat-view-servlet:
        enabled: true
        login-password: 123
        login-username: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js, *.gif, *.jpg, *.png, /druid/*'

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  web:
    resources:
      # Linux
      static-locations: "file:/usr/local/detect"
      # Windows
      #static-locations: "file:E:"
mybatis:
  mapper-locations: classpath:mapper/*.xml

path:
  # Linux
  save-image-path: "/usr/local/detect/images/"
  url-prefix: "http://8.136.84.248:8083"

